### ISSUE TITLE
No release on rubygems

### ISSUE THREAD

**Issue by dsander** [mistydemeo/fasttrack#1]
Hi @mistydemeo,

thanks for writing fasttrack and exempi! We are planning to use them in production but need a release on rubygems for that. Would you mind pushing the current version of both gems to rubygems?

regards,

Dominik

**Comment by mistydemeo** [comment]
Sure, absolutely! I'll try to get that done soon.

**Comment by mistydemeo** [comment]
They're both published! :sparkles: 

What are you using them in, out of curiosity?

**Comment by dsander** [comment]
Thanks! :clap: 

We will be using them to synchronize the XMP metadata of media files between Adobe Premiere and our [production asset management software](http://www.flavoursys.com/products/strawberry-4/).
